// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuB3ptirfgRneK9sYjVhI6oZl5u9RaCeE',
    appId: '1:954786342818:web:d238994804c72d23e1f4fb',
    messagingSenderId: '954786342818',
    projectId: 'miage-projet',
    authDomain: 'miage-projet.firebaseapp.com',
    storageBucket: 'miage-projet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQc1DBV6iqYgnqkfdcF5UA1uZZ0RoY_QI',
    appId: '1:954786342818:android:09ec081e81c31a7de1f4fb',
    messagingSenderId: '954786342818',
    projectId: 'miage-projet',
    storageBucket: 'miage-projet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwUAg4uDTpKOrNO_aq2AupkfnISNSIuYg',
    appId: '1:954786342818:ios:d3833d31f5f539cee1f4fb',
    messagingSenderId: '954786342818',
    projectId: 'miage-projet',
    storageBucket: 'miage-projet.appspot.com',
    iosBundleId: 'com.example.projetMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwUAg4uDTpKOrNO_aq2AupkfnISNSIuYg',
    appId: '1:954786342818:ios:c985569211409061e1f4fb',
    messagingSenderId: '954786342818',
    projectId: 'miage-projet',
    storageBucket: 'miage-projet.appspot.com',
    iosBundleId: 'com.example.projetMobile.RunnerTests',
  );
}
